version: '3'
services:
  db:
    container_name: mongodbacademia
    image: mongo:6.0.6
    ports:
      - 27020:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: rafael
      MONGO_INITDB_ROOT_PASSWORD: 123456789
      MONGO_INITDB_DATABASE: academia
    volumes:
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro